const Phonlog=[
    {
        id:1,
        name:"Nishanth",
        img:require('../assets/images/incoming.png'),
        phno:"8951406478",
        desc:"You have receieved the call",
        startTime:"9 Am",
        endTime:"9:05 Am",
        TotalDuration:"5 minutes 3 seconds",
    },
    {
        id:2,
        name:"Anudeep",
        img:require('../assets/images/blocked.png'),
        phno:"8762339086",
        desc:"You have blocked the call",
        startTime:"8 Am",
        endTime:"8 Am",
        TotalDuration:"0 minutes 0 seconds",
    },
    {
        id:3,
        name:"Tejas G K",
        img:require('../assets/images/didntAccept.png'),
        phno:"9480987928",
        desc:"You didnt recieve the call",
        startTime:"7 Am",
        endTime:"7 Am",
        TotalDuration:"0 minutes 0 seconds",
    },
    {
        id:4,
        name:"Ayush",
        img:require('../assets/images/incoming.png'),
        phno:"7892275270",
        desc:"You have receieved the call",
        startTime:"9 pm",
        endTime:"9:30 pm",
        TotalDuration:"30 minutes 12 seconds",
    },
    {
        id:5,
        name:"Chethan",
        img:require('../assets/images/outgoing.png'),
        phno:"8431083047",
        desc:"You have called this number",
        startTime:"4 pm",
        endTime:"4:12 Am",
        TotalDuration:"12 minutes 03 seconds",
    },
    {
        id:6,
        name:"Abhishekh",
        img:require('../assets/images/didntAccept.png'),
        phno:"9756945372",
        desc:"You didnt receieve the call",
        startTime:"12 pm",
        endTime:"12 pm",
        TotalDuration:"0 minutes 0 seconds",
    },
    {
        id:7,
        name:"Abhiram",
        img:require('../assets/images/didntAccept.png'),
        phno:"9865467876",
        desc:"You didnt receieve the call",
        startTime:"11 am",
        endTime:"11 am",
        TotalDuration:"0 minutes 0 seconds",
    },
]

export default Phonlog